[package]
name = "pfd"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies.rocket]
version = "0.5.0-rc.1"
features = [ "json" ]

[dependencies.rusqlite]
version = "0.25.3"
features = [ "bundled" ]
