[package]
name = "rocket-rates"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies.rocket]
version = "0.5.0-rc.1"
features = [ "json" ]

[dependencies.rocket_sync_db_pools]
version = "0.1.0-rc.1"
features = ["sqlite_pool"]

[dependencies.rusqlite]
version = "0.25.3"
features = [ "bundled" ]

[dependencies.reqwest]
version = "0.11"

[dependencies.zip]
version = "0.5"
