[default]
provider = "ecb"
databases.main.url = "rates.db"

[[default.migrations]]
version = 1
up = """
CREATE TABLE exchange_rate (
    quote TEXT NOT NULL,
    base TEXT NOT NULL,
    rate REAL NOT NULL
)
"""
down = "DROP TABLE exchange_rate"

[[default.migrations]]
version = 2
up = "CREATE UNIQUE INDEX idx_exchange_rate_quote_base ON exchange_rate (quote, base)"
down = "DROP INDEX idx_exchange_rate_quote_base"
