[default.databases.main]
url = "rates.db"

[default.providers.fiat.ecb]
enabled = true
schedule = "0 0 14 * * * *"

[default.providers.crypto.iex]
enabled = true
schedule = "0 0,15,30,45 * * * * *"

[[default.migrations]]
version = 1
up = """
CREATE TABLE exchange_rate (
    quote TEXT NOT NULL,
    base TEXT NOT NULL,
    rate REAL NOT NULL
)
"""
down = "DROP TABLE exchange_rate"

[[default.migrations]]
version = 2
up = "CREATE UNIQUE INDEX idx_exchange_rate_quote_base ON exchange_rate (quote, base)"
down = "DROP INDEX idx_exchange_rate_quote_base"

[[default.migrations]]
version = 3
up = """
CREATE TABLE user (
    id TEXT PRIMARY KEY
);
INSERT INTO user (id) VALUES ('91c12d49-8577-4f42-b49d-0a0cfcfa1b85');
"""
down = "DROP TABLE user"
