[default]
provider = "ecb"
databases.main.url = "rates.db"

[[default.migrations]]
version = 1
up = """
CREATE TABLE exchange_rate (
    base TEXT NOT NULL,
    quote TEXT NOT NULL,
    rate REAL NOT NULL
)
"""
down = "DROP TABLE exchange_rate"

[[default.migrations]]
version = 2
up = "CREATE UNIQUE INDEX idx_exchange_rate_base_quote ON exchange_rate (base, quote)"
down = "DROP INDEX idx_exchange_rate_base_quote"
